version: '3'
services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend